### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by zmohammad01**
broken link @g-may

### CODE REVIEW

**Comment by zmohammad01** [comment]
fyi @SirSpidey

**Comment by SirSpidey** [comment]
`DomainName` is correct here, but it's just missing the closing `}

**Comment by zmohammad01** [comment]
Ah okay. Just had to pass this link to someone so figured this might be the quicker thing. 

But thanks for the correction/observation. 

Regards,
Zia Mohammad

**Comment by g-may** [comment]
Thanks Zia 👍  fixed this on the internal repo

**Pull request closed without merging**
